const keyMirror = require("keymirror");

const ActionTypes = keyMirror({
  SCRAPER_CONNECTED: null,
  CONTENT_SCRAPED: null,
  SPAWN_SCRAPER: null,
  STOP_SCRAPERS: null,
  FRONTEND_STATUS_RECEIVED: null,
  SCRAPER_STATUS_CHANGED: null,
  SCRAPER_SPAWNED: null,
  DOWNLOADS_SYNC_REQUESTED: null,
  DOWNLOADS_WAITING_FOR_SYNC: null,
  DOWNLOADS_SYNC_RECEIVED: null,
  BACKEND_STATUS_CHANGED: null,
  JOBS_BATCH_SCRAPED: null,
  LOCATION_UPDATED: null,
  SNAPSHOT_CONFIG_UPDATED: null,
  SCRAPE_LOCATION_BY_TERM_REQUESTED: null,
});

export default ActionTypes;
